/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Restaurant;

public class Restaurant {

    private String name;
    private int starsNum;
    private String priceCategory;
    private Review review;


    public Restaurant(String name ,int starsNum, String priceCategory, Review review) {
        this.name=name;
        this.starsNum=starsNum;
        this.priceCategory=priceCategory;
        this.review=review;

    }
    public Restaurant(String name ,int starsNum, String priceCategory) {
        this.name=name;
        this.starsNum=starsNum;
        this.priceCategory=priceCategory;

    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getStarsNum() {
        return starsNum;
    }

    public void setStarsNum(int starsNum) {
        this.starsNum = starsNum;
    }

    public String getPriceCategory() {
        return priceCategory;
    }

    public void setPriceCategory(String priceCategory) {
        this.priceCategory = priceCategory;
    }

    public String getReview() {
        return review.toString();
    }

    public void addReview(String body, String author, int starsNum ) {
        this.review= new Review(body,author,starsNum);
        this.starsNum= starsNum;
    }



    @Override
    public String toString() {
        return "Restaurant Details{" +
                "Restaurant Name='" + name + '\'' +
                ", Number of stars=" + starsNum +
                ", Price Category='" + priceCategory + '\'' +
                '}';
    }

}
