/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Restaurant;
import Restaurant.Restaurant;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RestaurantTest {
/*
test of the Restaurant class
*/
@Test
    public void tostringTest() {
        Restaurant capital= new Restaurant("Capital Restaurant",2,"dollar");
        assertEquals("Restaurant Details{Restaurant Name='Capital Restaurant', Number of stars=2, Price Category='dollar'}", capital.toString(),"ensure that its toString is working properly");

    }
    @Test
    public void testResturant(){
        Restaurant capital= new Restaurant("Capital Restaurant",2,"dollar");
        assertEquals("Capital Restaurant", capital.getName(), "Implement a Restaurant constructor. ");
    }
    /*
test of the Review  class
*/
    @Test
    public void reviewtostringTest() {
        Review review = new Review("the restaurant is good","Ahmad Ali",3);
        assertEquals("Review on the Restaurant Service: {comment='the restaurant is good', By:'Ahmad Ali', Evaluation Stars Num=3}", review.toString(),"ensure that its toString is working properly");

    }
    // Test that your constructor is working reasonably.
    @Test
    public void testreview(){
        Review review = new Review("the restaurant is good","Ahmad Ali",3);
        assertEquals("Ahmad Ali", review.getAuthor(), "Test that your constructor is working reasonably.\n");
    }
    @Test
    public void addReviewTest(){
        Restaurant capital= new Restaurant("Capital Restaurant",2,"dollar");
        capital.addReview("the restaurant is good","Ahmad Ali",3);
        assertEquals("Review on the Restaurant Service: {comment='the restaurant is good', By:'Ahmad Ali', Evaluation Stars Num=3}", capital.getReview());
    }
    @Test
    public void updateStarTest(){
        Restaurant capital= new Restaurant("Capital Restaurant",2,"dollar");
        capital.addReview("the restaurant is good","Ahmad Ali",3);
        assertEquals(3, capital.getStarsNum(),"check updating the restaurant evaluation ");
    }

}

